@startuml

!theme cerulean

class Address {
   Streetname: varchar(50)
   HouseNumber: int
   PostCode: int
   Suburb: varchar(50)
   lon: float
   lat: float
   StolpersteinID: int
   AddressID: int
}
class Photo {
   lat: float
   Heading: varchar(10)
   lon: float
   Approved: boolean
   UserID: int
   StolpersteinID: int
   approveUserID: int
   PhotoID: int
}
class Role {
   Role_name: varchar(15)
   RoleID: int
}
class Stolperstein {
   Description: varchar(255)
   Approved: boolean
   UserID: int
   VictimID: int
   StolpersteinID: int
}
class Users {
   password: varchar(30)
   login_email: varchar(50)
   Name: varchar(30)
   Last_Name: varchar(30)
   RoleID: int
   UserID: int
}
class Victim {
   Name: varchar(30)
   Last_Name: varchar(30)
   Date_of_birth: date
   Date_of_death: date
   VictimID: int
}

Address       -[#595959,plain]-^  Stolperstein : "StolpersteinID"
Photo         -[#595959,plain]-^  Stolperstein : "StolpersteinID"
Photo         -[#595959,plain]-^  Users        : "approveUserID:UserID"
Photo         -[#595959,plain]-^  Users        : "UserID"
Stolperstein  -[#595959,plain]-^  Users        : "UserID"
Stolperstein  -[#595959,plain]-^  Victim       : "VictimID"
Users         -[#595959,plain]-^  Role         : "RoleID"
@enduml
