version: '3.8'

services:
  postgres:
    image: kartoza/postgis:16-3.4--v2023.11.04
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakPW
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:latest
    volumes:
      - ./imports:/opt/bitnami/keycloak/data/import
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloakPW
      - KEYCLOAK_EXTRA_ARGS=--import-realm
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local