version: '3.8'

services:
  postgres:
    image: kartoza/postgis:16-3.4--v2023.11.04
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakPW
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:latest
    volumes:
      - ./imports:/opt/bitnami/keycloak/data/import
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloakPW
      - KEYCLOAK_EXTRA_ARGS=--import-realm
    depends_on:
      - postgres

  arproject-fe:
    image: wermar/arproject-fe:latest
    ports:
      - "80:80"
    depends_on:
      - arproject-be

  arproject-be:
    container_name: arproject-be
    image: wermar/arproject-be:latest
    ports:
      - "443:8580"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local