drop table if exists Photo;
drop table if exists Stolperstein;
drop table if exists User;
drop table if exists Role;
drop table if exists Address;
drop table if exists Victim;
drop table if exists databasechangelog;
drop table if exists databasechangeloglock;
drop table if exists overpass_stolperstein;