spring:
  profiles:
    active: development
    group:
      development:
        - database

  # Liquibase Configuration
  liquibase:
    drop-first: false
    enabled: true
    contexts: development

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: backend-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost/realms/arStolpersteine
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost/realms/arStolpersteine