spring:
  profiles:
    active: development
    group:
      development:
        - database

  # Liquibase Configuration
  liquibase:
    drop-first: false
    enabled: true
    contexts: development

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${backend.keycloak.base}/certs
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: backend-client
            client-secret: tlzRiERgcCepxEQiXyr2iPc5GpwCjoGw
        provider:
          keycloak:
            authorization-uri: : ${backend.keycloak.base}/authorize
            token-uri: ${backend.keycloak.base}/token

backend:
  keycloak:
    serverUrl: "http://:localhost/auth"
    realm: arStolpersteine
    base: ${backend.keycloak.serverUrl}/realms/${backend.keycloak.realm}/protocol/openid-connect
  rest:
    security:
      allowList:
        - /security/**
        - /error
        - /swagger-ui/**
        - /v3/api-docs*/***
        - /webjars/**

server:
  port: 8580

