openapi: 3.0.0
info:
  title: Public AR-Stolperstein API
  description: This is the Public OpenAPI Specification for the AR-Stolpersteine Backend. Every Endpoint is without an Authentication accessible
  version: 1.0.0
paths:
  /api/public/stolpersteine:
    get:
      tags:
        - Public
      summary: Get Stolpersteine in a specific radius
      description: Get Stolpersteine in a specific radius (e.g. 500m)
      operationId: getStolpersteineForUser
      parameters:
        - name: radius
          in: query
          description: Area around current User-Location
          required: true
          schema:
            type: integer
            description: Number represent radius in meters
            example: 200
        - name: latUser
          in: query
          description: Lat-Coordinate from current User-Location
          required: true
          schema:
            type: number
            format: float
            example: 90.233232
        - name: lngUser
          in: query
          description: Lng-Coordinate from current User-Location
          required: true
          schema:
            type: number
            format: float
            example: 45.233232
      responses:
        200:
          description: return all stolpersteine based on current user location and radius
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StolpersteineResponseDto'
        400:
          description: Bad Request - All Query-Params need to be set
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        404:
          description: If no Stolpersteine for UserId was found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        500:
          description: Internal Server Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
    post:
      tags:
        - Secured
      summary: Create a new Stolpersteine for given userId
      description: Get all available Stolpersteine for an User
      operationId: addStolpersteinForUser
      parameters:
        - name: userId
          in: path
          description: ID of User
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StolpersteineReqDto'
      responses:
        200:
          description: return created stolpersteine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StolpersteineResponseDto'
        400:
          description: Bad Request when no valid request was send
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        500:
          description: Internal Server Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
  /api/secured/stolpersteine/update/{stolpersteinId}:
    put:
      tags:
        - Secured
      summary: Update a existing Stolpersteine
      description: Update a existing Stolperstein for given Id
      operationId: updateStolpersteine
      parameters:
        - name: stolpersteinId
          in: path
          description: ID of explicit Stolperstein
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StolpersteineReqDto'
      responses:
        200:
          description: update was successfully and return updated object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StolpersteineResponseDto'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        404:
          description: When a Stolperstein is not existing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        500:
          description: Internal Server Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
  /api/secured/requests:
    get:
      tags:
        - Secured
      summary: Load all existing Requests
      description: Load all existing Requests for adding Stolperstein-Informations to the System
      operationId: getStolpersteinRequests
      responses:
        200:
          description: all existing requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponseDto'
        403:
          description: Forbidden - the Resource is only available for a specific role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
  /api/secured/requests/{requestId}/approve:
    post:
      tags:
        - Secured
      summary: Approve Request for Id
      description: Approve referenced Request and activate Stolperstein
      operationId: approveRequest
      parameters:
        - name: requestId
          in: path
          description: ID of Request
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Request is approved and Stolperstein active
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponseDto'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        404:
          description: Request for Id was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        403:
          description: Forbidden - the Resource is only available for a specific role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
  /api/secured/requests/{requestId}/reject:
    post:
      tags:
        - Secured
      summary: Reject Request for Id
      description: Reject referenced Request and don't activate Stolperstein
      operationId: approveRequest
      parameters:
        - name: requestId
          in: path
          description: ID of Request
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  nullable: false
                  type: string
                  description: Reason why Request is rejected
                  example: Die Bilder entsprechen nicht unseren Richtlinien.
                  maxLength: 512
                informRequester:
                  type: boolean
                  description: If the requester should be informed, that the Request is rejected
      responses:
        200:
          description: Request is reject
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponseDto'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        404:
          description: Request for Id was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        403:
          description: Forbidden - the Resource is only available for a specific role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDto'
components:
  schemas:
    ProblemDto:
      type: object
      properties:
        errorCode:
          type: integer
          example: 400
        description:
          type: string
          example: Bad Request - Missing Parameter
    VictimReqDto:
      type: object
      required:
        - firstname
        - lastname
        - dateOfBirth
        - dateOfDeath
      properties:
        firstname:
          type: string
          example: Max
        lastname:
          type: string
          example: Mustermann
        dateOfBirth:
          type: string
          format: date
          example: 1933-12-21
        dateOfDeath:
          type: string
          format: date
          example: 1942-02-23
    AddressReqDto:
      type: object
      required:
        - streetName
        - houseNumber
        - postCode
      properties:
        streetName:
          type: string
          example: Mustermann-Strasse
        houseNumber:
          type: string
          maxLength: 4
          minLength: 1
          example: 12a
        postCode:
          type: string
          maxLength: 5
          minLength: 5
          example: 97074
        city:
          type: string
          example: Wuerzburg
    PhotoReqDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 232
    StolpersteineReqDto:
      type: object
      required:
        - description
        - position
        - victim
      properties:
        description:
          type: string
          example: That is an example of a stolperstein description
        position:
          type: object
          required:
            - lat
            - lng
          properties:
            lat:
              type: number
              format: float
              example: 90.233232
            lng:
              type: number
              format: float
              example: 23.232232
        victim:
          $ref: '#/components/schemas/VictimReqDto'
        address:
          $ref: '#/components/schemas/AddressReqDto'
        photos:
          type: array
          items:
            $ref: '#/components/schemas/PhotoReqDto'

    VictimResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 232
        firstname:
          type: string
          example: Max
        lastname:
          type: string
          example: Mustermann
        dateOfBirth:
          type: string
          format: date
          example: 1933-12-21
        dateOfDeath:
          type: string
          format: date
          example: 1942-02-23
    AddressResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 232
        streetName:
          type: string
          example: "Mustermannstrasse"
        houseNumber:
          type: string
          maxLength: 4
          minLength: 1
          example: 12a
        postCode:
          type: string
          maxLength: 5
          minLength: 5
          example: 97074
        city:
          type: string
          example: Wuerzburg
    PhotoResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 232
        heading:
          type: integer
          description: representing the heading on a compass for N, W, E, S
          format: int16
          example: 90
        resourceUrl:
          type: string
          description: specific path to resource to download the file
          example: "/232/example-crypt-3s2323.jpeg"
        resourceGroup:
          type: string
          description: representing the group where all available resources can be loaded as once
          example: "/232"
    StolpersteineResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1023
        description:
          type: string
          example: That is an example of a stolperstein description
        position:
          type: object
          properties:
            lat:
              type: number
              format: float
              example: 90.233232
            lng:
              type: number
              format: float
              example: 23.232232
        victim:
          $ref: '#/components/schemas/VictimResponseDto'
        address:
          $ref: '#/components/schemas/AddressResponseDto'
        photos:
          type: array
          items:
            $ref: '#/components/schemas/PhotoResponseDto'
    RequestResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 3232
        status:
          type: string
          enum:
            - REQUESTED
            - APPROVED
            - REJECTED
        requester:
          type: object
          properties:
            firstname:
              type: string
              example: Max
            lastname:
              type: string
              example: Mustermann
        requestedStolperstein:
          $ref: '#/components/schemas/StolpersteineResponseDto'


